yetanalytics/lrs-admin-ui

Makefile, resources/sass/global.scss, resources/sass/xapi.scss, src/com/yetanalytics/lrs_admin_ui/functions/http.cljs, src/com/yetanalytics/lrs_admin_ui/subs.cljs, src/com/yetanalytics/lrs_admin_ui/views/accounts.cljs, src/com/yetanalytics/lrs_admin_ui/views/browser.cljs
- Visual cleanup and spacing around inputs on account and credentials
- Header cleanups in browser
- Filters separated and displayed
- better URL view
-
=> SQL-111, 112, 115, 116, 123 

src/com/yetanalytics/lrs_admin_ui/views/footer.cljs
Clicking the text would do nothing on the first three nav buttons. just nesting the text inside `a`
=> text of mobile nav links was not active, only icon was.

resources/public/index.html, src/com/yetanalytics/lrs_admin_ui/core.cljs, src/com/yetanalytics/lrs_admin_ui/handlers.cljs, src/com/yetanalytics/lrs_admin_ui/subs.cljs, src/com/yetanalytics/lrs_admin_ui/views/menu.cljs
reworked db to take envs from server. 
Also disable stmt browser tab when enable-html is false
=> SQL-127 (server envs) UI-side

resources/sass/xapi.scss
changed to center from baseline, and did a few tweaks to make that work
https://user-images.githubusercontent.com/54323005/144109385-5bf2dbc5-6fbc-49f1-bb31-48fdba74aa80.mov
=> CSS changes to reflect lrs-60

src/com/yetanalytics/lrs_admin_ui/views/browser.cljs, src/com/yetanalytics/lrs_admin_ui/views/credentials/api_key.cljs
[SQL-168] add state scope to UI. See https://github.com/yetanalytics/lrsql/pull/280
[SQL-168]: https://yet.atlassian.net/browse/SQL-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-168 add state scope

deps.edn
These: https://github.com/yetanalytics/lrs-admin-ui/security/dependabot
=> resolve multiple vulnerabilities

src/com/yetanalytics/lrs_admin_ui/views/accounts.cljs
[SQL-184] Give account items a natural key so the right one is removed from the DOM on delete.
[SQL-184]: https://yet.atlassian.net/browse/SQL-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-184 Delete Account Bug

resources/sass/global.scss, src/com/yetanalytics/lrs_admin_ui/db.cljs, src/com/yetanalytics/lrs_admin_ui/handlers.cljs, src/com/yetanalytics/lrs_admin_ui/input.cljs, src/com/yetanalytics/lrs_admin_ui/subs.cljs, src/com/yetanalytics/lrs_admin_ui/views/accounts.cljs, src/com/yetanalytics/lrs_admin_ui/views/header.cljs, src/com/yetanalytics/lrs_admin_ui/views/main.cljs, src/com/yetanalytics/lrs_admin_ui/views/update_password.cljs
[SQL-187] Provide a facility for admin accounts to update their own passwords.
SQL LRS PR: https://github.com/yetanalytics/lrsql/pull/295
[SQL-187]: https://yet.atlassian.net/browse/SQL-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-187 update password UI

src/com/yetanalytics/lrs_admin_ui/db.cljs, src/com/yetanalytics/lrs_admin_ui/functions/http.cljs, src/com/yetanalytics/lrs_admin_ui/handlers.cljs, src/com/yetanalytics/lrs_admin_ui/subs.cljs
- Support an additional path prefix for proxy situations
- One hitch is the /env call itself. If it's in dev or has a set host it will do full path but in prod with admin already redirected/loaded it will use a relative call to keep up with the proxy.
=> [SQL-213] support for variable nested paths set by env

resources/sass/reactions.scss, src/com/yetanalytics/lrs_admin_ui/functions/time.cljs, src/com/yetanalytics/lrs_admin_ui/views/reactions.cljs
- Aligned button nav
- click-to-view rows w/hover behavior
- edit/delete action icons
TODO:
- inner conditional styling
- nested clause box styling
- Reaction info space usage
[Screencast from 01-08-2024 11:35:53 AM.webm](https://github.com/yetanalytics/lrs-admin-ui/assets/54323005/8f6f961b-00e5-48ae-a38d-55a43981d737)
=> 211 style modifications #1

resources/sass/global.scss, src/com/yetanalytics/lrs_admin_ui/views/reactions.cljs
Added Tooltips to Reactions feature
https://github.com/yetanalytics/lrs-admin-ui/assets/54323005/887df8b2-5897-4a8c-a454-92a024202adf
=> Sql 217 - Tooltips!

src/com/yetanalytics/lrs_admin_ui/handlers.cljs, src/com/yetanalytics/lrs_admin_ui/spec/reaction_edit.cljs, src/com/yetanalytics/lrs_admin_ui/views/reactions.cljs
[SQL-225] Fix bug where an empty condition would lead to a spec error when adding a new condition.
[SQL-225]: https://yet.atlassian.net/browse/SQL-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-225 Empty condition bug

src/com/yetanalytics/lrs_admin_ui/views/reactions.cljs
count operation keys only, instead of elements. Also simplified logic.
=> SQL-226 - Bug with shading for nested NOT clause

resources/sass/global.scss, src/com/yetanalytics/lrs_admin_ui/views/form.cljs, src/com/yetanalytics/lrs_admin_ui/views/form/dropdown.cljs, src/com/yetanalytics/lrs_admin_ui/views/form/validation.cljs, src/com/yetanalytics/lrs_admin_ui/views/reactions.cljs, src/com/yetanalytics/lrs_admin_ui/views/reactions/path.cljs, src/com/yetanalytics/lrs_admin_ui/views/reactions/template.cljs
Image paths needed some help in bundled version.
Also some light unrelated CSS
=> SQL 227 - Image paths for bundled/transpiled FE version

resources/sass/reactions.scss, src/com/yetanalytics/lrs_admin_ui/handlers.cljs, src/com/yetanalytics/lrs_admin_ui/views/reactions.cljs, src/com/yetanalytics/lrs_admin_ui/views/reactions/path.cljs, src/com/yetanalytics/lrs_admin_ui/views/reactions/template.cljs
- 229: Pre-open path segments for incomplete logic paths
- Changed text and ordering for clause types
- Added to needed subclause error messages
- Changed button text
https://github.com/yetanalytics/lrs-admin-ui/assets/54323005/deb70a05-7948-4c17-be0e-0bdf4c2b9037
=> [SQL-228 + SQL-229] - UI Review Changes

src/com/yetanalytics/lrs_admin_ui/db.cljs, src/com/yetanalytics/lrs_admin_ui/handlers.cljs
[SQL-230] Add a redirect when "no-val" auth is used.
[SQL-230]: https://yet.atlassian.net/browse/SQL-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SQL-230 add no-val logout redirect

src/com/yetanalytics/lrs_admin_ui/functions/scopes.cljs, src/com/yetanalytics/lrs_admin_ui/views/browser.cljs, src/com/yetanalytics/lrs_admin_ui/views/credentials/api_key.cljs
FE PR for https://github.com/yetanalytics/lrsql/pull/366. Also includes a refactoring of scope-related code into its own namespace, mainly to reduce duplication.
=> [SQL-170] Implement Profile Scopes

package-lock.json
=> update NPM deps

.github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/deps.yml, package-lock.json, package.json, resources/sass/bootstrap-upgrade-shim.scss, resources/sass/global.scss, resources/sass/login.scss, resources/sass/style.scss, src/com/yetanalytics/lrs_admin_ui/views/accounts.cljs, src/com/yetanalytics/lrs_admin_ui/views/update_password.cljs
bootstrap 5 modifications to maintain design. included a shim for now for a couple deprecated styles.
Only hiccup change was rows now fullwidth their child so a few sloppy rows had multiple things and that was no good, so wrapped them in divs.
Was also forced to add (just from build fails):
- Webpack Update (non-breaking)
- Actions updates
=> Bootstrap 5 CVN Update + Other Deps

package-lock.json
=> fix audit vuln

.github/workflows/ci.yml, test.cljs.edn
Add a hilarious amount of flags which together stop CI from hanging in Chromium 135.0.7012.0
=> Fix Chromium in CI

src/com/yetanalytics/lrs_admin_ui/db.cljs, src/com/yetanalytics/lrs_admin_ui/handlers.cljs, src/com/yetanalytics/lrs_admin_ui/views/browser.cljs
Reverts yetanalytics/lrs-admin-ui#104
A new PR will be created with the changes.
=> Revert "auth through proxy---CredentialID in url params"
